In [ ]:
# Check Version
import numpy as np
print(np.__version__)

1.19.5


In [ ]:
import numpy as n
a = n.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
# Check Type
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# Check Shape
print(a.shape)

(6,)


In [ ]:
# Creat array using List & Tuple
import numpy as np
a = np.array([1,2,2,3,3,5])
print(a)
print(type(a))

b = np.array((1,2,2,3,3,5))
print(b)
print(type(b))

[1 2 2 3 3 5]
<class 'numpy.ndarray'>
[1 2 2 3 3 5]
<class 'numpy.ndarray'>


In [ ]:
# Creat array using List & Tuple
l1 =  [11,12,13,14,15]
a1 = np.array(l1)
print(a1)
print(type(l1))
print(type(a1))

t1 =  (11,12,13,14,15)
a11 = np.array(t1)
print(a11)
print(type(t1))
print(type(a11))

In [ ]:
# O dimesnion Array
import numpy as np
arr = np.array(40)
print(arr)
print(arr.shape) 

40
()


In [ ]:
# 1 dimesnional Array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.shape) 

[1 2 3 4 5]
(5,)


In [ ]:
# 2 dimesnional Array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr) 
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# 3 dimesnional Array
import numpy as np
#arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])
print(arr) 
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [1 2 3]]
(3, 3)


In [ ]:
# Checking the Dimensions of the arrays
import numpy as np

a = np.array(40)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim) 

0
1
2
3


In [ ]:
# n Dimensuional Array
import numpy as np
arr = np.array([1, 2, 3, 4,5,6,8], ndmin=2)
np.array
print(arr)
print(arr.shape)
print('number of dimensions :', arr.ndim) 

[[1 2 3 4 5 6 8]]
(1, 7)
number of dimensions : 2


In [ ]:
# Array Indexing
import numpy as np
arr = np.array([1, 2, 3, 4])

print(arr[0]) 
print(arr[-1])
print(arr[-2])
print(arr[2])

In [ ]:
# Array Slicng
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10])

print(arr[1:5]) 
print(arr[:3])
print(arr[2:])
print(arr[-3:])
print(arr[::2])

[2 3 4 5]
[1 2 3]
[ 3  4  5  6  7  8  9 10]
[ 8  9 10]
[1 3 5 7 9]


In [ ]:
# Slicing in 2 dimesnional Array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
#print(arr) 
#print(arr.shape)
print(arr[1:2,1:2])

[[5]]


In [ ]:
# Copy the array
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
a = arr
# print(arr)
# print(a)
a[0] = 11
print(a)
print(arr)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
a = arr.copy()
print(arr)
print(a)
a[0] = 11
print(a)
print(arr)

[11  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# Reshape Array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,12])
newarr = arr.reshape(4,3)
print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Reshape Array
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr) 

In [ ]:
#Iterating a Array
import numpy as np
arr = np.array([1, 2, 3,4,5])
for x in arr:
  print(x) 

In [ ]:
#Iterating a 2D Array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x) 

[1 2 3]
[4 5 6]


In [4]:
# Join two arrays
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)
# Aritmatic Operation
print(arr1 + arr2) 
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 * 2)
print(arr1 - 2)

[1 2 3 4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[2 4 6]
[-1  0  1]


In [ ]:
#Split the array in 2 parts:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 5)
print(newarr) 

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [ ]:
# Sort the array
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
print(arr)
arr[::-1].sort()
print(arr)
print(arr[0])

[0 1 2 3]
[3 2 0 1]
[3 2 1 0]
3


In [ ]:
arr = np.array([3, 2, 0, 1])
for x in (len(arr)):
  l = arr[x]
  if arr[x+1] > arr[x]:
    l = arr[x+1]
print(l) 


In [ ]:
#Arange Function
a1 = np.arange(5,15,2)
print(a1)

[ 5  7  9 11 13]


In [ ]:
#Arange Function
a1 = np.arange(1,15,2)
print(a1)
arr1=np.arange(0,10)

[ 1  3  5  7  9 11 13]


In [ ]:
# Line Space function
import numpy as np
a2 = np.linspace(1,10,5)
print(a2)

# restep set to True
print(np.linspace(2.0, 3.0, num=10))


In [10]:
# rand function (0 to 1)
print(np.random.rand(3,5))
print(np.random.rand(4))
print(np.random.rand(5))

[[0.88639489 0.19294337 0.89366461 0.83766089 0.21617963]
 [0.38652248 0.39810121 0.62723545 0.68271207 0.14930777]
 [0.63438871 0.59683921 0.07495942 0.90655631 0.31748099]]
[0.41917669 0.9766601  0.07912487 0.90725475]
[0.25609538 0.71749171 0.03259733 0.07643076 0.36239905]


In [ ]:
# rand function
np.random.randint(1,10,6)

array([3, 1, 2, 3, 2, 6])

In [ ]:
# rand function
arr_ex=np.random.randn(2,3)
print(arr_ex)

[[ 1.90248369 -0.39715936  0.09774795]
 [-1.61905595  0.57679565 -0.0458513 ]]


In [ ]:
# random_sample (0.0, to 1.0)
import numpy as np
val = np.random.random_sample()
print ("Output random float value : ", val)

Output random float value :  0.5075450560080207


In [ ]:
# Create array of zeros and ones
#print(np.zeros(5))
#print(np.zeros(5,dtype=int))
#print(np.zeros((2,5),dtype=int))
print(np.zeros((2,3,4),dtype=int))

In [ ]:
# Create array ones
#print(np.ones(5))
#print(np.ones(5,dtype=int))
#print(np.ones((2,5),dtype=int))
print(np.ones((2,3,4),dtype=int))

In [ ]:
# other function
arr = np.array([3, 2, 5, 1])
arr1 = np.array([3, 1, 5, 1])
np.sqrt(arr)
np.maximum(arr,arr1)


array([3, 2, 5, 1])

In [ ]:
# Identity Matrix
import numpy as np
i = np.eye(4,4)
print(i)
print(np.eye(3,3))


In [ ]:
#Horizontal Stacking of Numpy Arrays
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

o = np.hstack((a1, a2))

print(o)

In [ ]:
#Vertically Stacking of Numpy Arrays
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])
o = np.vstack((a1, a2))
print(o)

In [ ]:
#Getting the positions (indexes) where elements of 2 numpy arrays match
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])
print(np.where(a == b))

In [ ]:
#Matrix Generation with one particular value
o = np.full((3, 3), 7)
print(o)

In [ ]:
#Matrix Transpose
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

a_transpose = a.T

print(a_transpose)

In [ ]:
# rand function
print(np.random.randint(1,10,5))
print(np.random.randint(1,10, size=(3,3)))